/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

export const GET_SEARCH_LIST_SUCCESS = 'GET_SEARCH_LIST_SUCCESS';
export const GET_SEARCH_LIST_FAILED = 'GET_SEARCH_LIST_FAILED';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';
